### ISSUE TITLE
Error thrown when spec finishes for new Cypress 10

### ISSUE THREAD

**Issue by CassenH** [reportportal/agent-js-cypress#116]
I'm getting this error right then the first spec finishes for Cypress Version 10.0.3

```
Channel closed
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:371:5)
    at ChildProcess.target.send (node:internal/child_process:721:16)
    at Runner.<anonymous> (/e2e/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:115:21)
    at Runner.emit (node:events:402:35)
    at Runner.emit (node:domain:475:12)
    at Reporter.emit (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/server/lib/reporter.js:362:46)
    at Object.onMocha (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/server/lib/project-base.js:283:34)
    at Socket.<anonymous> (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/server/lib/socket-base.js:250:40)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at Socket.emitUntyped (/root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
    at /root/.cache/Cypress/10.0.3/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by notfounnd** [comment]
@CassenH in an overview, I understand this agent ins't compatible with Cypress 10.

RP agent uses cypress.json to resolve its setup. The new version of Cypress changed config file format.
- cypress.json --> cypress.config.js

You can see here: https://docs.cypress.io/guides/references/changelog#10-0-0

**Comment by AmsterGet** [comment]
Hello @CassenH @notfounnd !
Please see https://github.com/reportportal/agent-js-cypress/issues/115
Any contribution is greatly appreciated 😄

**Comment by praveentata** [comment]
I see the same error with Cypress 10.
The error shows up immediately when the specs are run using tags using `cypress-tags` library.
When running one `spec` file, it runs for sometime and then throws the same error.

Any help is appreciated.
Thanks :)

**Comment by orgads** [comment]
I pushed #126 (a revised version of #123), which fixes the issue.

Until this is merged, I created a forked package @audc/reportportal-agent-js-cypress.

You can install it without any code changes by: `npm install @reportportal/agent-js-cypress@npm:@audc/reportportal-agent-js-cypress`.

Once the fix is merged in and released, you can switch back to the original package.

**Comment by AmsterGet** [comment]
Hello guys!
The version 5.1.0 released with Cypress 10.x support. Please [try it](https://www.npmjs.com/package/@reportportal/agent-js-cypress).
Thanks to @orgads and @dwentland24 !
