### ISSUE TITLE
Auto merge: plugin is not installed. Use reporterOptions settings for calculation. Configuration property not set! Neither for cypress <= 9 nor cypress >= 10

### ISSUE THREAD

**Issue by praveentata** [reportportal/agent-js-cypress#175]
I see that this issue was submitted: https://github.com/reportportal/agent-js-cypress/issues/170
but was closed without an answer.

I am curious to know if others are also having the same problem or encountered the same problem and how they fixed it

Cypress version: 13.3.0
Report Portal Version: 5.1.3

cypress.config.js:
```javascript
const { defineConfig } = require("cypress");
const registerReportPortalPlugin = require('@reportportal/agent-js-cypress/lib/plugin');
const { tagify } = require("cypress-tags");

module.exports = defineConfig({
  reporter: "@reportportal/agent-js-cypress",
  reporterOptions: {
    endpoint: 'http://localshot:8080/api/v1',
    apiKey: 'apiKey',
    launch: 'LAUNCH_NAME',
    project: 'PROJECT_NAME',
    description: 'Description',
    autoMerge: true,
  },
  defaultCommandTimeout: 300000,
  responseTimeout: 300000,
  pageLoadTimeout: 300000,
  headless: false,
  numTestsKeptInMemory: 1,
  chromeWebSecurity: false,
  viewportHeight: 1080,
  viewportWidth: 1920,
  video: false,
  videoCompression: false,
  videoUploadOnPasses: false,
  screenshotOnRunFailure: true,
  experimentalSessionSupport: true,
  screenshotsFolder: 'cypress/screenshots',
  env: {
    dev: {
      baseUrl: 'url',
      username: 'username',
      password: 'password',
    },
    uat: {
      baseUrl: 'url',
      username: 'username',
      password: 'password',
    },
  },
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      // return require('./cypress/plugins/index.js')(on, config)
      on('file:preprocessor', tagify(config));
      on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chrome') {
          console.log('Adding --disable-dev-shm-usage...');
          launchOptions.args.push('--disable-dev-shm-usage');
        }

        return launchOptions;
      });
      return registerReportPortalPlugin(on, config);
    },
    specPattern: 'cypress/e2e/**/**_spec.js',
    excludeSpecPattern: [
      '**/login_spec.js',
      '**/lighthouse_audit_spec.js',
    ],
  },
});
```

Error:

```
Auto merge: plugin is not installed. Use reporterOptions settings for calculation.
Configuration property not set! Neither for cypress <= 9 nor cypress >= 10
Error: Configuration property not set! Neither for cypress <= 9 nor cypress >= 10
    at getTotalSpecs (/automation/folder/node_modules/@reportportal/agent-js-cypress/lib/utils.js:228:11)
    at CypressReporter.calcTotalLaunches (/Users/tatap/Git/UIAutomation/qa-ui-automation/s1-atlas/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:202:39)
    at L.<anonymous> (/automation/folder/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:155:23)
    at L.emit (node:events:525:35)
    at S.emit (<embedded>:4515:16494)
    at Object.onMocha (<embedded>:4562:27715)
    at p.<anonymous> (<embedded>:4515:45184)
    at p.emit (node:events:513:28)
    at <embedded>:4515:24385
```

**Comment by praveentata** [comment]
So, it seems like the `cypress-tags` library is causing this issue.
When I don't use the `CYPRESS_INCLUDE` flag in my command, it works fine and `autoMerge` error goes away.
This library also seemed to be interfering with `@aws-sdk` libraries and causing the following issue: https://github.com/aws/aws-sdk-js-v3/issues/5349

For now, I have stopped using the `cypress-tags` library to move forward

**Comment by praveentata** [comment]
Update: It worked initially without the `cypress-tags` library but I am facing the same issue when I specify the `--spec <file_name>` in the command. So, this doesn't seem completely related to the `cypress-tags` library.
It will be great if someone can look into it

Thanks

**Comment by Zenin-Dmitry** [comment]
Hi!
I have the same problems.
no errors
`npx cypress run`
error exists
`npx cypress run --spec cypress/e2e/*cy.js`
Have you found how to run tests from the required folders?

**Comment by Zenin-Dmitry** [comment]
I studied the problem a little and this is the result. I run it with this command
_npx cypress run --spec cypress/e2e/api/endpoints/Attributes/test1.cy.js_
There is no error in this test, data is sent
```
describe('Test_describe', ()=> {
it ('Test1',() => {
    cy.visit('/')
    })
})
```
There is an error in this test
```
describe('Test_describe', ()=> {
it ('Test1',() => {
    cy.request('/')
    })
})
```

**Comment by diegoarena** [comment]
Hi.
Any update on this ? I'm having the same issue using cypress 13
`npx cypress run --browser chrome --env grepTags=@login,grepFilterSpecs=true,grepOmitFiltered=true`
`Auto merge: plugin is not installed. Use reporterOptions settings for calculation.
Configuration property not set! Neither for cypress <= 9 nor cypress >= 10
Error: Configuration property not set! Neither for cypress <= 9 nor cypress >= 10
    at getTotalSpecs (/home/diego/Documents/trabajo/revai/web-e2e-tests/node_modules/@reportportal/agent-js-cypress/lib/utils.js:229:11)
    at CypressReporter.calcTotalLaunches (/home/diego/Documents/trabajo/revai/web-e2e-tests/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:205:39)
    at L.<anonymous> (/home/diego/Documents/trabajo/revai/web-e2e-tests/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:158:23)
    at L.emit (node:events:525:35)
    at A.emit (<embedded>:4479:18259)
    at Object.onMocha (<embedded>:4526:27943)
    at p.<anonymous> (<embedded>:4479:47429)
    at p.emit (node:events:513:28)
    at <embedded>:4479:26630`
Thanks!

**Comment by niQo** [comment]
same issue using cypress 13 and  [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) when the first test containt tag @skip

**Comment by xpersky** [comment]
I've also encountered this error on cypress 13.6.1 with webpack preprocessor, as far as I managed to debug the problem, it seems that ipc connection did not succeed to retry on time, therefore changing:

``` 
lib/plugin/ipcClient.js:28
  ipc.config.retry = 1500;
```

To anything close to 100 seem to be working fine each time.

**Comment by Zenin-Dmitry** [comment]
@xpersky Your solution is interesting, but I run tests in Docker and install packages with the command npm ci.
Of course, you can change this line in the container, but it seems to me that we need to look for another solution.
@AmsterGet  Here are my settings
```
reporterOptions: {
    endpoint: 'http://mydomen.local:8080/api/v1',
    apiKey: 'tests_bUazvjzBQeywFoQvHH',
    launch: 'AAA',
    project: 'AAA',
    description: process.env.CI_JOB_URL || 'autotest Cypress',
    debug: true,
    "autoMerge": true,
    attributes: [
      { key: "runType",
        value: process.env.CI_PIPELINE_SOURCE || "Manual"
      },
      { key: "branch",
        value: process.env.CI_COMMIT_BRANCH || "Unknown"
      },
      { key: "commit",
        value: process.env.CI_COMMIT_SHORT_SHA || "Unknown"
      },
      { 
        value: process.env.CI_JOB_NAME || "Unknown"
      },       
    ],
  },
```

**Comment by chelseablake4** [comment]
I am also seeing this issue, but intermittently and I have been trying to debug why with no luck.

Running in docker file:
`sh """
                  docker run \
                    -v "$WORKSPACE:REDACTED" \
                    -v REDACTED \
                    -w REDACTED \
                    -e "NO_COLOR=1" \
                    -e "RP_LAUNCH=REDACTED" \
                    -e "RP_DESCRIPTION=REDACTED" \
                    -e "RP_ENV=REDACTED" \
                    -e "RP_BRANCH=REDACTED" \
                    -e "RP_MODE=DEFAULT" \
                    cypress/included:13.10.0 \
                    --config-file "REDACTED.ts" \
                    --config video=false,screenshotOnRunFailure=false
                """`
With reporter options set to:
` reporter: '@reportportal/agent-js-cypress',
    reporterOptions: {
        endpoint: process.env.REDACTED,
        apiKey: process.env.REDACTED,
        launch: process.env.REDACTED,
        project: process.env.REDACTED,
        description: process.env.REDACTED,
        autoMerge: 'true',
        mode: process.env.REDACTED,
        debug: true,
        attributes: [
            {
                key: 'REDACTED',
                value: 'REDACTED'
            {
                key: 'REDACTED',
                value: 'REDACTED',
            },
            {
                key: 'REDACTED',
                value: 'REDACTED',
            },
            {
                key: 'REDACTED',
                value: 'REDACTED',
            },
        ],
    },`

I am only seeing this issue intermittently when running through Jenkins (never when running locally) and I have yet to pin point why that is.
