### ISSUE TITLE
Project does not build on Mac M1

### ISSUE THREAD

**Issue by llanni** [reportportal/agent-js-cypress#210]
Hi,

I have imported and integrated your project in my cypress git project, anyway when I run it, I get this error.
I tried many things but none fixed it. Not even sure if it is related to your project or the dependency microtime.

Attached the log with the error.

Thanks for your help.

npm run cy:run

> qaroots-website@1.0.0 cy:run
> cypress run

DevTools listening on ws://127.0.0.1:49739/devtools/browser/1529afa7-aac6-44c9-b88a-5235f2c1ac99
Error loading the reporter: @reportportal/agent-js-cypress

We searched for the reporter in these paths:

 - /Users/l2l/qaroots/website/@reportportal/agent-js-cypress
 - /Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress

Learn more at https://on.cypress.io/reporters

Error: dlopen(/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/microtime/prebuilds/darwin-x64+arm64/electron.napi.node, 0x0001): tried: '/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/microtime/prebuilds/darwin-x64+arm64/electron.napi.node' (code signature in <0597889B-E5ED-385D-B003-3B76F9B3F07C> '/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/microtime/prebuilds/darwin-x64+arm64/electron.napi.node' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/microtime/prebuilds/darwin-x64+arm64/electron.napi.node' (no such file), '/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/microtime/prebuilds/darwin-x64+arm64/electron.napi.node' (code signature in <0597889B-E5ED-385D-B003-3B76F9B3F07C> '/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/microtime/prebuilds/darwin-x64+arm64/electron.napi.node' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2107)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2107)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at PackherdModuleLoader.origLoad (node:electron/js2c/node_init:2:13357)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755811)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at load (/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/microtime/index.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at PackherdModuleLoader.origLoad (node:electron/js2c/node_init:2:13357)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755811)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/node_modules/@reportportal/client-javascript/lib/helpers.js:4:19)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at PackherdModuleLoader.origLoad (node:electron/js2c/node_init:2:13357)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755811)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/lib/utils/objectCreators.js:18:23)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at PackherdModuleLoader.origLoad (node:electron/js2c/node_init:2:13357)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755811)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/lib/utils/index.js:19:24)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at PackherdModuleLoader.origLoad (node:electron/js2c/node_init:2:13357)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755811)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:43:5)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at PackherdModuleLoader.origLoad (node:electron/js2c/node_init:2:13357)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755811)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/l2l/qaroots/website/node_modules/@reportportal/agent-js-cypress/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at PackherdModuleLoader.origLoad (node:electron/js2c/node_init:2:13357)
    at PackherdModuleLoader.tryLoad (evalmachine.<anonymous>:1:755811)
    at Function.<anonymous> (evalmachine.<anonymous>:1:766025)
    at i._load (<embedded>:2970:67438)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at A.loadReporter (<embedded>:2975:21800)
    at C.initializeReporter (<embedded>:3028:27000)
    at C.startWebsockets (<embedded>:3028:27304)
    at C.open (<embedded>:3028:25601)
    at async v.create (<embedded>:3028:40000)
    at async L (<embedded>:3028:79238)
    at async J (<embedded>:3028:93355)

**Comment by AmsterGet** [comment]
Hi @llanni !
The issue looks very close to another described [here](https://github.com/reportportal/client-javascript/issues/217).
We tested this on the M1, but it looks like some specifics may affect the installation.
Meanwhile please use the [agent-js-cypress version 5.3.5](https://github.com/reportportal/agent-js-cypress/releases/tag/v5.3.5) while executing on M-series processors and track the progress in the mentioned issue.
