### ISSUE TITLE
TypeError: createMergeLaunchLockFile is not a function

### ISSUE THREAD

**Issue by albadam000** [reportportal/agent-js-cypress#53]
Following error occurs after updating to @reportportal/agent-js-cypress 5.0.0:

****/node_modules/@reportportal/agent-js-cypress/lib/reporter.js:68
      createMergeLaunchLockFile(launch, tempId);
      ^

TypeError: createMergeLaunchLockFile is not a function
    at Reporter.runStart (/Users/1077260/Documents/source/Platform/cypress-canary-tests/node_modules/@reportportal/agent-js-cypress/lib/reporter.js:68:7)
    at process.<anonymous> (/Users/1077260/Documents/source/Platform/cypress-canary-tests/node_modules/@reportportal/agent-js-cypress/lib/worker.js:41:16)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
    ✓ Can open *** website (3057ms)
Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at Runner.<anonymous> (/Users/1077260/Documents/source/Platform/cypress-canary-tests/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:137:19)
    at Runner.emit (events.js:215:7)
    at Reporter.emit (/Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:263:54)
    at Object.onMocha (/Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:381:18)
    at Socket.<anonymous> (/Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:313:32)
    at Socket.emit (events.js:210:5)
    at /Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at Runner.<anonymous> (/Users/1077260/Documents/source/Platform/cypress-canary-tests/node_modules/@reportportal/agent-js-cypress/lib/cypressReporter.js:137:19)
    at Runner.emit (events.js:215:7)
    at Reporter.emit (/Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:263:54)
    at Object.onMocha (/Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:381:18)
    at Socket.<anonymous> (/Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:313:32)
    at Socket.emit (events.js:210:5)
    at /Users/1077260/Library/Caches/Cypress/4.9.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by ElenaRomanchuk** [comment]
Will be fixed in scope of #54
