### ISSUE TITLE
Fail to start launch Error: Request failed with status code 502

### ISSUE THREAD

**Issue by vishallanke** [reportportal/agent-js-cypress#56]
int.json
```
 "reporterOptions": {
    "configFile": "reporter-config.json"
  },
```

reporter-config.json
```
{
  "reporterEnabled": "mochawesome, @reportportal/agent-js-cypress,  mocha-junit-reporter",
  "reporterOptions": {
    "mochawesomeReporterOptions": {
      "mochaFile": "cypress/results/results-[hash].xml",
      "reportDir": "cypress/artifacts/reports/",
      "reportFilename": "value",
      "reportTitle": "value ",
      "overwrite": false,
      "html": true,
      "timestamp": true,
      "json": true
    },
    "reportportalAgentJsCypressReporterOptions": {
      "endpoint": "http://emter amazpon ec2 url.compute.amazonaws.com:8080/api/v1",
      "token": "token",
      "launch": "cypress",
      "project": "cypress_project",
      "description": "END_TO_END",
      "isLaunchMergeRequired": false,
      "autoMerge": true,
      "integrationFolder": "cypress/integration",
      "screenshotsFolder": "cypress/screenshots",
      "fixturesFolder": "cypress/fixtures",
      "supportFile": "cypress/support/index.js",
      "pluginsFile": "cypress/plugins/index.js"
    }
  }
}
```

When executed from Git Pipeline, we are getting below errors
```
Error: Request failed with status code 502
     at /home/cypress_testing/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
 Fail to start launch Error: Request failed with status code 502
     at /home/cypress_testing/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
 Fail to start suite Error: Request failed with status code 502
     at /home/cypress_testing/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
 Fail to start suite Error: Request failed with status code 502
     at /home/cypress_testing/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
 Fail to start test Error: Request failed with status code 502
     at /home/cypress_testing/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by evjlobanova** [comment]
@AmsterGet Could you please check

**Comment by AmsterGet** [comment]
This seems to be a standard Bad Gateway error. Could you please check for RP server availability or server access from the git pipeline itself.

**Comment by vishallanke** [comment]
Server is accessible from Gitlab.
If I remove Mocha reporting / JUnit reporting and keep only report portal agent, then it works well

**Comment by vishallanke** [comment]
If you see below defect https://github.com/reportportal/agent-js-cypress/issues/37
I am using same RP server, same Gitlab, at-least not getting 502 error.
But when I use this along with Mocha reporting, I am getting error

**Comment by vishallanke** [comment]
Please close this issue, seems some sporadic network problem ...
