### ISSUE TITLE
Launch "undefined" not found

### ISSUE THREAD

**Issue by maluyvova** [reportportal/agent-js-cypress#9]
Error: Launch "undefined" not found
    at RPClient.finishLaunch (/node_modules/reportportal-client-restler/lib/report-portal-client.js:171:55)
    at ReportPortalReporter.finishLaunch (/node_modules/agent-js-cypress/rp-reporter.js:75:41)
    at Runner.ReportPortalReporter.runner.on (/node_modules/agent-js-cypress/rp-reporter.js:65:18)
    at emitOne (events.js:116:13)
    at Runner.emit (events.js:211:7)
    at Reporter.emit (/Users/vbariletti/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:237:55)
    at Object.server.startWebsockets.onMocha (/Users/vbariletti/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:300:22)
    at Socket.<anonymous> (/Users/vbariletti/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:236:36)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /Users/vbariletti/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

it fails in finishLaunch but I couldn’t find where this method is called from, I provided all changes that described in ReadMe, but it still fails
I tried to debug and observe that launchTempId, finishExecutionRQ is undefined
oh and also i see it logs results on the endpoint, so I can see the launch on the dashboard

**Comment by alexeiser** [comment]
I am seeing this as well when we Cypress runs with more than 14 tests (the number is variable but always after 30 tests, it fails).

Low number of tests work fine.

**Comment by rbdodds-tango** [comment]
I'm seeing a similar issue whenever there is a 'fail' event in the before all hook.

**Comment by cypressher** [comment]
Started hitting this issue recently when running cypress suites. They just end abruptly with the error as mentioned above. Any help or suggestions will be greatly appreciated!

**Comment by ElenaRomanchuk** [comment]
Hi @maluyvova, @alexeiser. @rbdodds-tango, @cypressher,
We have just released the new version of cypress reporter as a new package @reportportal/agent-js-cypress: https://www.npmjs.com/package/@reportportal/agent-js-cypress. You can try it now.
Please, let us know if this solves your issue.

**Comment by evjlobanova** [comment]
Please reopen issue, if it is still reproduced
